[tool.black]
line-length = 79
include = '\.pyi?$'
exclude = '''
/(
		\.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | migrations
  | frontend
  | requirements
  | static
  | templates
  | build
  | dist
  | upload
)/
'''
